# .golangci.yml

version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet              # Go's standard vet tool
    - staticcheck        # Replacement for several deprecated linters like gosimple, unused
    - errcheck           # Check for ignored errors
    - revive             # Style, naming, comments
    - ineffassign        # Detect unused variable assignments
    - unused             # Unused vars/functions/constants
    - nakedret           # Disallow naked returns (clarity)
    - gocritic           # Assorted correctness/style suggestions
    - prealloc           # Suggest preallocating slices
    - makezero           # Prefer `x = T{}` over `x = new(T)`
    - misspell
    - errname
    - gocritic
    - dupl
    - bodyclose
    - durationcheck
    - exhaustive
    - dupword
    - copyloopvar
    - errorlint
    - errchkjson
    - contextcheck
    - containedctx
    - decorder
    - embeddedstructfieldcheck
    - gosec
    - cyclop
  settings:
    gosec:
      excludes:
        - G115

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gofmt:
      simplify: true
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/mcphone2004/cache)
      local-prefixes: "github.com/mcphone2004/cache/"
